config/routes.rb
Rails.application.routes.draw do
  # `resources` keyword is Rails convention for adding a group of routes
  resources :albums do
    resources :songs
  end
end

app/models/album.rb
# albums GET      /albums(.:format)                albums#index
# POST            /albums(.:format)                albums#create
# new_album GET   /albums/new(.:format)            albums#new
# edit_album GET  /albums/:id/edit(.:format)       albums#edit
# album GET       /albums/:id(.:format)            albums#show
# PATCH           /albums/:id(.:format)            albums#update
# PUT             /albums/:id(.:format)            albums#update
# DELETE          /albums/:id(.:format)

class Album < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/album_artist.rb
class AlbumArtist < ApplicationRecord
  # naming convention dictates first class be singular, second class plural
  belongs_to :artist
  belongs_to :album
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  # File provides a place to put code that _all_ models inherit.
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :album_artists
  has_many :albums, :through => :album_artists
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album

  attr_accessor :lyrics
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
    render :index
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    # `save` returns a boolean while `create` returns the created record
    if @album.save
      redirect_to albums_path
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to albums_path
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_path
  end

  private

  def album_params
    # an example of "strong parameters", which lets our app know which params can be passed into our methods
    #`params.require(:<name-of-class>).permit(:<name-of-parameters-to-accept-separated-by-commas)`
    params.require(:album).permit(:name, :genre)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    @album = Album.find(params[:album_id])
    @song = @album.songs.new
    render :new
  end

  def create
    @album = Album.find(params[:album_id])
    @song = @album.songs.new(song_params)
    if @song.save
      redirect_to album_path(@album)
    else
      render :new
    end
  end

  def show
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:album_id])
    render :show
  end

  def edit
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])
    render :edit
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to album_path(@song.album)
    else
      @album = Album.find(params[:album_id])
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to album_path(@song.album)
  end

  private

  def song_params
    params.require(:song).permit(:name, :lyrics)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= form_for @album do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit %>
<% end %>

app/views/albums/index.html.erb
<h1>Albums</h1>

<% if @albums.any? %>
  <ul>
    <% @albums.each do |album| %>
      <li><%= link_to album.name, album_path(album) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no albums yet.</p>
<% end %>

<%= button_to "Create new album", new_album_path, method: :get %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= form_for @album do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit %>
<% end %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<h3><%= @album.genre %></h3>

<% if @album.songs.any? %>
  <h4>Here are the songs for this album:</h4>

  <% @album.songs.each do |song| %>
    <ul>
      <li>
        <%= link_to song.name, album_song_path(@album, song) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No songs are listed for this album.</p>
<% end %>

<%= button_to "Add Song to Album", new_album_song_path(@album), method: :get %>
<%= button_to "Edit Album", edit_album_path(@album), method: :get %>
<%= button_to "Delete Album", album_path(@album), method: :delete %>
<%= button_to "Return to Albums Page", albums_path, method: :get %>

app/views/layouts/_album_form.html.erb
<%= render "layouts/errors", :object => @album %>

<%= form_for @album do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if @album.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @album.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecordStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Edit song:</h1>

<%= form_for [@album, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name %>
  <%= f.label :lyrics %>
  <%= f.text_area :lyrics %>
  <p><%= f.submit %></p>
<% end %>

app/views/songs/new.html.erb
<h1>Add a new song:</h1>

<%= form_for [@album, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name %>
  <%= f.label :lyrics %>
  <%= f.text_area :lyrics %>
  <p><%= f.submit %></p>
<% end %>

app/views/songs/show.html.erb
<h1>Song: <%= @song.name %></h1>
<h2>Album: <%= @album.name %></h2>
<h3><%= @song.lyrics %></h3>

<% if @album.songs.any? %>
  <h4>Here are the songs for this album:</h4>

  <% @album.songs.each do |song| %>
    <ul>
      <li>
        <%= link_to song.name, album_song_path(@album, song) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No songs are listed for this album.</p>
<% end %>

<%= button_to "Edit Song", edit_album_song_path(@album, @song), method: :get %>
<%= button_to "Delete Song", album_song_path(@album, @song), method: :delete %>
<%= button_to "Return to Album", album_path(@album), method: :get %>